### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by alvroma** [jlowin/pyautodiff#2]
When I first tried installing the package (sudo python setup.py install), I came into a warning that said there was nothing in the build\lib.linux-x86_64-2.7 folder.
By changing the setup.py file to the following, I managed to get it to properly install. Not sure if this is due to my configuration or something else.

from setuptools import setup

setup(
    name='autodiff', #changed from pyautodiff
    version='0.3',
    maintainer='Lowin Data Company',
    maintainer_email='info@lowindata.com',
    description=('Automatic differentiation for NumPy.'),
    license='new BSD',
    url='https://github.com/LowinData/pyautodiff',
    packages=['autodiff','autodiff.compat'],  #added line
    long_description = open('README.md').read(),
    install_requires=['numpy', 'theano'],
    classifiers=[
        'Intended Audience :: Science/Research',
        'Intended Audience :: Developers',
        'License :: OSI Approved',
        'Programming Language :: Python',
        'Topic :: Software Development',
        'Topic :: Scientific/Engineering',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX',
        'Operating System :: Unix',
        'Operating System :: MacOS'
    ]
)

PS: great work by the way

**Comment by dhruvbhatia** [comment]
Same issue here.

**Comment by jlowin** [comment]
Thank you!
