### ISSUE TITLE
ypeError: slice indices must be integers or None or have an __index__ method on simple optimization example

### ISSUE THREAD

**Issue by gwtaylor** [jlowin/pyautodiff#6]
Hi Jeremiah,
I posted an issue about a year ago while teaching my grad class (which you helped resolve, thanks!). I am back to this class and testing a different example that worked on the older code base but no longer works. I am using the python2-ast tree [9df844a] because we're stuck on Python 2 here.

Running the example below currently fails with the error:

```
  File "/Users/gwtaylor/src/pyautodiff/autodiff/symbolic.py", line 99, in trace
    results = self.symfn(*c_args, **c_kwargs)
  File "<Context-AST>", line 488, in wrapper
  File "<Context-AST>", line 512, in vector_from_args
  File "<Context-AST>", line 45, in expandedcallargs
  File "<Context-AST>", line 23, in orderedcallargs
  File "<Context-AST>", line 901, in getcallargs
  File "<Context-AST>", line 817, in getargspec
  File "<Context-AST>", line 756, in getargs
TypeError: slice indices must be integers or None or have an __index__ method
```

deep in Context-AST which I can't seem to get into and debug with ipdb.
The example is working for me as far back as [c9c176f]. It stops working at [b454486] with a different error message, and this error message starts at [ee094b3].

I tried optimizing a much simpler function with the fmin_l_bfgs_b wrapper, and it worked, so I assume the optimization module is still intended for use.

Any insight you could lend would be much appreciated!

``` python
import numpy as np
from autodiff.optimize import fmin_l_bfgs_b

eps = np.finfo(np.double).eps  # -- a small number

dtype = 'float32'

# some fake data for this example
x = np.random.randn(100, 784)
y = np.random.randint(2, size=x.shape[0])


def logistic(u):
    """Return logistic sigmoid of float or ndarray `u`"""
    return 1.0 / (1.0 + np.exp(-u))


def p_y_given_x(W, b, x):
    return logistic(np.dot(x, W) + b)


def logreg_prediction(W, b, x):
    return p_y_given_x(W, b, x) > 0.5


def cross_entropy(x, z):
    # note we add a small epsilon for numerical stability
    return -(x * np.log(z + eps) + (1 - x) * np.log(1 - z + eps))


def logreg_cost(W, b, x, y):
    z = p_y_given_x(W, b, x)
    l = cross_entropy(y, z).mean(axis=0)
    return l

batch_criterion = lambda W, b: logreg_cost(W, b, x, y)

# initialize the model
W = np.zeros(x.shape[1], dtype=dtype)

# autodiff relies on the .size and .shape
# attributes, which native python types do not have
# need to create a numpy scalar
# note this is different than np.array([0.0])
# which will not broadcast
b = np.array(0.0)

W_new, b_new = fmin_l_bfgs_b(batch_criterion, (W, b))
```

**Comment by jlowin** [comment]
Hi Graham,

This was a very messy bug but I believe the code is now running on my machine. Perhaps you could clone the latest commit and try for yourself?

The Python 2 codebase is quite brittle. There are many corner cases that can trip it up (like this one!). The Python 3 codebase, while also fragile, was designed in a more robust way. I understand that you can't migrate but I just want to let you know that there may be other dangers lurking. In general, the more simple and explicit you make your code, the better change you'll have of succeeding.

By the way, @twiecki recently pointed me to a new AD package: http://pythonhosted.org//ad/index.html. I haven't used it yet but it does have an optimization interface and it's possible that it will succeed where pyautodiff fails (in particular in Python 2!). PyAutoDiff is designed to translate numpy code to Theano behind the scenes; the AD package deals with differentiable variables explicitly (but seems to do a lot of the work without user intervention). You may want to check it out as well!

**Comment by gwtaylor** [comment]
Hi Jeremiah,
Yes, this works! The timing is impeccable: I was planning on showing an example in class on Monday. Once again you've saved me.

Perhaps next year we'll migrate to Python 3 but the course is underway, so for now I will do what you say and keep everything pretty simple. Thanks for the pointer to the AD package. I did not know about it, so I'll check it out and also let the class know.
